ARG DIST=focal
FROM ubuntu:${DIST}
ARG APPNAME=risb
ARG BRANCH=3.0.x
ARG LLVM=10
ARG NCORES=4
ARG ARCH=x86-64
ARG NB_USER=hacker

SHELL ["/bin/bash", "-c"] 

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      clang-${LLVM} \
      cmake \
      g++ \
      gfortran \
      make \
      git \
      vim \
      lldb-${LLVM} \
      hdf5-tools \
      libclang-${LLVM}-dev \
      libc++-${LLVM}-dev \
      libc++abi-${LLVM}-dev \
      libomp-${LLVM}-dev \
      libgfortran4 \
      libgmp-dev \
      libboost-dev \
      libhdf5-dev \
      libblas-dev \
      liblapack-dev \
      libopenmpi-dev \
      libfftw3-dev \
      libnfft3-dev \
      openmpi-bin \
      openmpi-common \
      openmpi-doc \
      python3-clang-${LLVM} \
      python3-dev \
      python3-mako \
      python3-matplotlib \
      python3-mpi4py \
      python3-numpy \
      python3-scipy \
      python3-pip \
      jupyter-notebook \
      \
      sudo \
      openssh-client \
      curl \
      && \
    apt-get autoremove --purge -y && \
    apt-get autoclean -y && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*

ENV INSTALL_PREFIX=/home/${NB_USER}/triqs \
    PYTHONPATH=/usr/lib/python3.8/site-packages \
    CMAKE_PREFIX_PATH=/usr/lib/cmake/triqs \
    PYTHON_VERSION=3.8 \
    CC=clang-${LLVM} CXX=clang++-${LLVM} CXXFLAGS="-stdlib=libc++ -march=${ARCH}"

RUN useradd -u 1000 -m ${NB_USER} && \
    echo '${NB_USER} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ${NB_USER}
WORKDIR /home/${NB_USER}

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN mkdir src
RUN mkdir build && cd build && mkdir ${APPNAME}

# Insall triqs
RUN set -ex ; \
  for pkg in triqs ; do \
    git clone https://github.com/TRIQS/${pkg} --branch ${BRANCH} --depth 1 src/${pkg} ; \
    cd build ; mkdir ${pkg} ; cd ${pkg} ;\
    cmake ../../src/${pkg} -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} ; \
    make -j$NCORES ; \
    make install ; \
    cd .. ; cd .. ; \
  done
RUN echo "source ${INSTALL_PREFIX}/share/triqsvars.sh" >> /home/${NB_USER}/.bashrc

WORKDIR /home/${NB_USER}/build/${APPNAME}