services:
  risb:
    image: risb-dev
    container_name: risb
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - "../:/src/risb:ro"
      - "$HOME/tmp/risb_docs:/build/risb/docs/_build:rw"
    stdin_open: true # docker run -i
    tty: true # docker run -t
