name: Build

on:
  pull_request:
    branches:
      - main
      - unstable
  push:
    branches:
      - main
      - unstable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - {os: "ubuntu-22.04", python-version: "3.10", cc: "gcc", cxx: "g++", llvm: "15", gcc-version: "12"}
          #- {os: "ubuntu-22.04", python-version: "3.11", cc: "gcc", cxx: "g++", llvm: "15", gccversion: "12"}
          #- {os: "ubuntu-22.04", python-version: "3.10", cc: "clang", cxx: "clang++", llvm: "15", gcc-version: "12"}
          #- {os: "ubuntu-22.04", python-version: "3.11", cc: "clang", cxx: "clang++", llvm: "15", gcc-version: "12"}
  
    runs-on: ${{ matrix.os }}
    
    name: Test Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Python ${{ matrix.python-version }} and TRIQS
      uses: ./.github/actions/setup-triqs
      with:
        python-version: ${{ matrix.python-version }}
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
        llvm: ${{ matrix.llvm }}
        gcc-version: ${{ matrix.gcc-version }}
      
    - name: Install risb
      run: |
        source $TRIQS_INSTALL/share/triqs/triqsvars.sh
        python -m pip install -e .[test]
      
    - name: Test risb
      run: |
        source $TRIQS_INSTALL/share/triqs/triqsvars.sh
        python -m pytest