name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - unstable
  push:
    branches:
      - main
      - unstable

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - {os: ubuntu-latest, cc: gcc, cxx: g++}
          - {os: ubuntu-latest, cc: clang, cxx: clang++}
    uses: ./.github/workflows/triqs.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}

  tests:
    needs: build
    
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - {os: ubuntu-latest, cc: gcc, cxx: g++}
          - {os: ubuntu-latest, cc: clang, cxx: clang++}
      
    runs-on: ${{ matrix.os }}
    
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Only needed if using setuptools-scm
   
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      
      - name: Install package
        run: python -m pip install -e .[test]
      
      - name: Test package
        run: python -m pytest