name: Build TRIQS

on:
  workflow_call:

env:
  LLVM: 15
  GCC_VERSION: 12

jobs:

  build-triqs:

    strategy:
        fail-fast: true
        matrix:
          include:
            - {os: ubuntu-latest, cc: gcc-12, cxx: g++-12}
            - {os: ubuntu-latest, cc: clang-15, cxx: clang++-15}
  
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run:
          sudo apt-get update &&
          sudo apt-get install -y lsb-release wget software-properties-common &&
          wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh &&
          sudo chmod +x /tmp/llvm.sh &&
          sudo apt-get purge --auto-remove llvm python3-lldb-${LLVM} llvm-${LLVM} &&
          sudo /tmp/llvm.sh ${LLVM} &&
          sudo apt-get install
            clang-${LLVM}
            cmake 
            g++-${GCC_VERSION}
            gfortran 
            git 
            vim 
            lldb-${LLVM} 
            libclang-${LLVM}-dev 
            libc++-${LLVM}-dev 
            libc++abi-${LLVM}-dev 
            libomp-${LLVM}-dev 
            hdf5-tools 
            libfftw3-dev 
            libgfortran5 
            libgmp-dev 
            libhdf5-dev 
            libblas-dev 
            liblapack-dev 
            libboost-dev 
            libopenmpi-dev 
            openmpi-bin 
            openmpi-common 
            python3-clang-${LLVM} 
            python3-dev 
            python3-pip 
            python3-mako 
            python3-mpi4py 
            python3-h5py 
            python3-numpy 
            python3-scipy 

      - name: install TRIQS
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          git clone https://github.com/TRIQS/triqs
          mkdir triqs/build && cd triqs/build
          cmake .. -DBuild_Documentation=OFF -DBuild_Tests=OFF -DCMAKE_INSTALL_PREFIX=/usr/ 
          make -j1 install VERBOSE=1
          sudo make install
          cd ../ 